#!/usr/bin/env python3
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
MATRIX=ROOT/'data/triform-migration-matrix.json'

def main():
    data=json.loads(MATRIX.read_text(encoding='utf-8'))
    entries=data.get('entries',[]); repos=[e.get('repository') for e in entries]; by={e.get('repository'):e for e in entries}; f=[]
    if data.get('schema')!='admissible-existence.triform-migration-matrix/v2': f.append('unexpected_schema')
    if data.get('registry_repository_count')!=32: f.append('registry_repository_count_mismatch')
    if len(entries)!=32: f.append('entry_count_mismatch')
    if len(set(repos))!=len(repos): f.append('duplicate_repository')
    expected=['Admissible-Existence/Existence','Admissible-Existence/GTG','Admissible-Existence/ET','Admissible-Existence/learning-transition-governance','Admissible-Existence/BC','Admissible-Existence/CHF','Admissible-Existence/RE','Admissible-Existence/RE-Reduction']
    if data.get('completed_source_migrations')!=8: f.append('completed_source_migration_count_mismatch')
    if data.get('completed_source_repositories')!=expected: f.append('completed_source_repository_set_mismatch')
    if by.get('Admissible-Existence/Existence',{}).get('triform_state')!='BOUNDED_TRIFORM_COMPLETE_MERGED': f.append('existence_completion_not_recorded')
    gtg=by.get('Admissible-Existence/GTG',{})
    if gtg.get('triform_state')!='BOUNDED_TRIFORM_COMPLETE_MERGED_HISTORICAL_COLLISION_OPEN': f.append('gtg_completion_or_collision_state_mismatch')
    if gtg.get('historical_gtg_a1_a8_equivalence')!='NOT_ESTABLISHED': f.append('gtg_historical_equivalence_must_remain_not_established')
    et=by.get('Admissible-Existence/ET',{})
    if et.get('triform_state')!='BOUNDED_TRIFORM_COMPLETE_MERGED_SEMANTIC_EXCLUSIONS': f.append('et_completion_or_exclusion_state_mismatch')
    if et.get('excluded_historical_equivalence_principles')!=['ET-AUTHORITY-003','ET-TEMPORAL-004']: f.append('et_semantic_exclusion_set_mismatch')
    if et.get('historical_source_replacement') is not False: f.append('et_historical_source_replacement_must_remain_false')
    ltg=by.get('Admissible-Existence/learning-transition-governance',{})
    if ltg.get('triform_state')!='BOUNDED_TRIFORM_COMPLETE_MERGED': f.append('ltg_completion_not_recorded')
    if ltg.get('identity_capture') is not False: f.append('ltg_identity_capture_must_remain_false')
    if ltg.get('predetermined_intellectual_destination') is not False: f.append('ltg_predetermined_destination_must_remain_false')
    if ltg.get('authority_effect') is not False: f.append('ltg_authority_effect_must_remain_false')
    bc=by.get('Admissible-Existence/BC',{})
    if bc.get('triform_state')!='BOUNDED_TRIFORM_COMPLETE_MERGED': f.append('bc_completion_not_recorded')
    if bc.get('bounded_principle_count')!=4: f.append('bc_bounded_principle_count_mismatch')
    if bc.get('bounded_identifier_provenance')!='NEW_BINDING_IDS_NOT_HISTORICAL_SOURCE_IDS': f.append('bc_identifier_provenance_mismatch')
    if bc.get('authority_effect') is not False: f.append('bc_authority_effect_must_remain_false')
    chf=by.get('Admissible-Existence/CHF',{})
    if chf.get('triform_state')!='BOUNDED_TRIFORM_COMPLETE_MERGED': f.append('chf_completion_not_recorded')
    if chf.get('bounded_principle_count')!=4: f.append('chf_bounded_principle_count_mismatch')
    if chf.get('bounded_identifier_provenance')!='NEW_BINDING_IDS_NOT_HISTORICAL_SOURCE_IDS': f.append('chf_identifier_provenance_mismatch')
    if chf.get('authority_effect') is not False: f.append('chf_authority_effect_must_remain_false')
    if chf.get('proof_promotion') is not False: f.append('chf_proof_promotion_must_remain_false')
    if chf.get('historical_source_replacement') is not False: f.append('chf_historical_source_replacement_must_remain_false')
    re=by.get('Admissible-Existence/RE',{})
    if re.get('triform_state')!='BOUNDED_TRIFORM_COMPLETE_MERGED_TESTED_NOT_PROVEN': f.append('re_completion_or_maturity_state_mismatch')
    if re.get('bounded_principle_count')!=5: f.append('re_bounded_principle_count_mismatch')
    if re.get('proof_maturity')!='tested_not_proven': f.append('re_proof_maturity_must_remain_tested_not_proven')
    if re.get('bounded_fixture_total')!=19: f.append('re_bounded_fixture_total_mismatch')
    if re.get('base_structural_checks')!=4: f.append('re_base_structural_check_count_mismatch')
    if re.get('universally_proven')!=0: f.append('re_universally_proven_must_remain_zero')
    if re.get('authority_effect') is not False: f.append('re_authority_effect_must_remain_false')
    if re.get('proof_promotion') is not False: f.append('re_proof_promotion_must_remain_false')
    if re.get('standing_bypass') is not False: f.append('re_standing_bypass_must_remain_false')
    if re.get('receipt_history_erasure') is not False: f.append('re_receipt_history_erasure_must_remain_false')
    if re.get('historical_source_replacement') is not False: f.append('re_historical_source_replacement_must_remain_false')
    rr=by.get('Admissible-Existence/RE-Reduction',{})
    if rr.get('triform_state')!='BOUNDED_TRIFORM_COMPLETE_MERGED': f.append('re_reduction_completion_not_recorded')
    if rr.get('bounded_principle_count')!=5: f.append('re_reduction_bounded_principle_count_mismatch')
    if rr.get('bounded_identifier_provenance')!='NEW_BINDING_IDS_NOT_HISTORICAL_SOURCE_IDS': f.append('re_reduction_identifier_provenance_mismatch')
    if rr.get('standing_reentry_required') is not True: f.append('re_reduction_standing_reentry_must_be_true')
    if rr.get('lineage_preserved') is not True: f.append('re_reduction_lineage_preserved_must_be_true')
    if rr.get('execution_authority_granted') is not False: f.append('re_reduction_execution_authority_must_be_false')
    if rr.get('source_authority_assertion_forbidden') is not True: f.append('re_reduction_source_authority_assertion_must_be_forbidden')
    if rr.get('replay_output_must_match_expected') is not True: f.append('re_reduction_replay_match_must_be_true')
    if rr.get('failure_outcome')!='FAIL_CLOSED': f.append('re_reduction_failure_outcome_mismatch')
    if rr.get('source_replacement_authorized') is not False: f.append('re_reduction_source_replacement_must_be_false')
    if rr.get('authority_effect') is not False: f.append('re_reduction_authority_effect_must_be_false')
    if rr.get('proof_promotion') is not False: f.append('re_reduction_proof_promotion_must_be_false')
    if rr.get('standing_bypass') is not False: f.append('re_reduction_standing_bypass_must_be_false')
    if rr.get('receipt_history_erasure') is not False: f.append('re_reduction_receipt_history_erasure_must_be_false')
    if rr.get('historical_source_replacement') is not False: f.append('re_reduction_historical_source_replacement_must_be_false')
    tt=by.get('Admissible-Existence/TT',{}); stcm=by.get('Admissible-Existence/STCM',{})
    if data.get('logical_next_candidate')!='Admissible-Existence/TT': f.append('unexpected_logical_next_candidate')
    if data.get('logical_candidate_state')!='DEFER_ACTIVE_CANONICAL_CLAIM': f.append('tt_logical_candidate_must_be_deferred')
    if tt.get('triform_state')!='DEFER_ACTIVE_CANONICAL_CLAIM' or tt.get('claim_state')!='CLAIMED_FOR_INTEGRATION': f.append('tt_deferral_not_preserved')
    if stcm.get('triform_state')!='DEFER_ACTIVE_CANONICAL_CLAIM' or stcm.get('claim_state')!='CLAIMED_FOR_INTEGRATION': f.append('stcm_deferral_not_preserved')
    if data.get('next_executable_candidate') is not None: f.append('next_executable_candidate_requires_evidence_pass')
    if data.get('selection_evidence_state')!='EVIDENCE_PASS_REQUIRED': f.append('selection_evidence_state_mismatch')
    for e in entries:
        if not e.get('triform_state'): f.append(f"missing_triform_state:{e.get('repository')}")
    print(json.dumps({'schema':'admissible-existence.triform-migration-validation/v2','valid':not f,'entry_count':len(entries),'completed_source_migrations':data.get('completed_source_migrations'),'logical_next_candidate':data.get('logical_next_candidate'),'logical_candidate_state':data.get('logical_candidate_state'),'next_executable_candidate':data.get('next_executable_candidate'),'selection_evidence_state':data.get('selection_evidence_state'),'findings':f,'authority_effect':'NONE_VALIDATION_ONLY'},indent=2,sort_keys=True))
    raise SystemExit(0 if not f else 1)

if __name__=='__main__': main()
